In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats as st
import math
np.set_printoptions(suppress=True)
import ML_function

In [2]:
df = pd.read_csv('pakistan.csv')
df.head()

,date,GDP Per capita,Prevalence of undernourishment (% of population),"Life expectancy at birth, total (years)"
0,2019-01-01,4888.845087,12.9,67.273
1,2018-01-01,4853.266557,12.2,67.114
2,2017-01-01,4571.205078,12.1,66.947
3,2016-01-01,4410.006565,12.4,66.770
4,2015-01-01,4373.014475,12.8,66.577

In [3]:
X = df[['GDP Per capita','Prevalence of undernourishment (% of population)']]
X

    GDP Per capita  Prevalence of undernourishment (% of population)
0      4888.845087                                              12.9
1      4853.266557                                              12.2
2      4571.205078                                              12.1
3      4410.006565                                              12.4
4      4373.014475                                              12.8
5      4238.633867                                              13.9
6      4103.629564                                              15.1
7      4018.732737                                              15.9
8      3993.559367                                              15.9
9      3890.290619                                              15.9
10     3868.743942                                              15.9
11     3818.071985                                              15.8
12     3766.855562                                              15.8
13     3579.962432                                              16.4
14     3357.363426                                              17.6
15     3127.690769                                              19.0
16     2898.032983                                              21.0
17     2753.540740                                              21.8
18     2709.027901                                              21.1

In [4]:
Y = df[['Life expectancy at birth, total (years)']]
Y.shape

(19, 1)

In [5]:
ML_function.ML_regression(X,Y)

Coefficients:  [54.88897341528781, 0.002387655269639688, 0.07229738168175182]
SSE:  [1.8404148621671164]
MSE:  [0.10825969777453626]
SE:  0.32902841484366707
t-stat:  2.1098155778331806
Lower CI's:  47.1489108066258
Lower CI's:  0.001322560016963966
Lower CI's:  -0.15860037901194696
Upper CI's:  62.629036023949816
Upper CI's:  0.0034527505223154098
Upper CI's:  0.3031951423754506
t-values:  [14.961844240542174, 4.729635466617758, 0.6606133452764745]
Null hypothesis rejected.
Null hypothesis rejected.
Failed to reject the null hypothesis.